### ISSUE TITLE
milestone 2 tasks

### ISSUE THREAD

**Issue by QuintenVervynck** [SELab-2/OSOC-4#331]
- [ ] tag & release
- [x] restructure user manual
- [x] in README link naar hoog niveau documentatie van de architectuur en ontwerp
- [x] gedetailleerde documentatie in de code
- [x] technische handleiding voor (lokale) installatie, hoe de testen uit te voeren, etc (bij voorkeur in de README van het project)
- [x] Een gebruikershandleiding in pdf (er moet hiernaar verwezen worden in het algemene README bestand in de root van de repository)
- [x] zorg voor testen
- [x] `documenteer de architecuur met onderstaande diagrammen`
- [x] deployment diagram (verschillende lagen en gebruikte technologiën per laag) + communicatie tussen de lagen
- [x] component/module overview:  overzicht + korte beschrijving van de belangrijkste componenten/modules/services in jullie ontwerp (b.v. een login service, data access service, Web UI,...) en in welke laag elke service zich bevindt en met welke andere services er gecommuniceerd wordt
- [x] `Documenteer het ontwerp met onderstaande diagrammen`
- [x] ~~Klassendiagrammen: structuur van belangrijkste klassen tonen (niet 1 groot diagram, maar een aantal diagrammen die elk focussen op een bepaald aspect van de software)~~
- [x] Interactie of sequence diagrammen, waarop de belangrijkste object interacties getoond worden  (Het is dus niet nodig om diagrammen van alle interacties te maken, maar volstaat op te focussen op de belangrijkste en meest complexe interacties)

other tasks: 

- [x] update domain model
- [x] update containers model
- [x] update design/architecture model
